// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "postgresql://postgres:H8kYpTzX1fCg3vRj7dNmLqB5eA0sWjIu@localhost:5432/crm_db?schema=public",
  },
});
